spring:
  rabbitmq:
    queue: mail-service.mail.send
    exchange: mail-service.mail.ex
    routing-key: mail.send
  data:
    mongodb:
      uri: mongodb://admin:verysecret@localhost:27017/finance_tracker?authSource=admin
      auto-index-creation: true
      database: finance_tracker
server:
  port: 8282