spring:
  rabbitmq:
    queue: mail-service.mail.send
    exchange: mail-service.mail.ex
    routing-key: mail.send
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MY_EMAIL}
    password: ${MY_EMAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
server:
  port: 8181