spring:
  rabbitmq:
    queue: mail-service.mail.send
    exchange: mail-service.mail.ex
    routing-key: mail.send
  mail:
    host: smtp.gmail.com
    port: 587
    username: finance.tracker3@gmail.com
    password: 'ecypeltlquimjqse'
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
server:
  port: 8282