spring:
  data:
    rabbitmq:
      queue: mail-service.mail.send
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MY_EMAIL}
    password: ${MY_EMAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
    default-encoding: UTF-8
server:
  port: 8181
