version: "3"

services:
  mongodb:
    image: 'mongo:6.0-jammy'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
      - 'MONGO_INITDB_ROOT_PASSWORD=verysecret'
      - 'MONGO_INITDB_DATABASE=database'
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
volumes:
  data:
