version: "3"

services:
  mongodb:
    image: 'mongo:6.0-jammy'
    container_name: mongo-db
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
      - 'MONGO_INITDB_ROOT_PASSWORD=verysecret'
      - 'MONGO_INITDB_DATABASE=database'
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbit-data:/var/lib/rabbitmq
  app:
    depends_on:
      - mongodb
      - rabbitmq
    build: ../backend
    container_name: app
    ports:
      - "8080:8080"


volumes:
  mongo-data:
  rabbit-data:
