version: "3"

services:
  mongodb:
    image: 'mongo:6.0-jammy'
    container_name: mongo-db
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
      - 'MONGO_INITDB_ROOT_PASSWORD=verysecret'
      - 'MONGO_INITDB_DATABASE=finance_tracker'
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init.js
      - mongo-data:/data/db
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbit-data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
  api-service:
    depends_on:
      - mongodb
      - rabbitmq
    build: ../backend
    container_name: app
    ports:
      - "8080:8080"
  report-service:
    depends_on:
      - mongodb
      - rabbitmq
    build: ../report-service
    container_name: report-service
    ports:
      - "8181:8181"
  mail-service:
    depends_on:
      - rabbitmq
    build: ../mail-service
    container_name: mail-service
    ports:
      - "8282:8282"

volumes:
  mongo-data:
  rabbit-data:
