spring:
  rabbitmq:
    queue: mail-service.mail.send
    exchange: mail-service.mail.ex
    routing-key: mail.send
  data:
    mongodb:
      uri: mongodb://admin:verysecret@localhost:27017/database?authSource=admin
      auto-index-creation: true
      database: database

finance-tracker:
  jwt:
    secret-key: 72357538782F4125442A472D4B6150645367566B597033733676397924422645
    expiration-ms: 86400000
    cookie-name: "finance-tracker-jwt"